//! USB gadget RNDIS network management.
//!
//! Manages the usb0 interface: static IP configuration, internet
//! connectivity checks, IP display rotation for the e-ink screen,
//! and periodic health monitoring.
//!
//! Replaces `usb0-fallback.service` and the NM connection profile.

use log::{info, warn};
use std::time::Instant;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// sysfs path for usb0 interface existence check.
pub const USB0_SYSFS_PATH: &str = "/sys/class/net/usb0";
/// sysfs path for usb0 link operstate.
pub const USB0_OPERSTATE_PATH: &str = "/sys/class/net/usb0/operstate";
/// Primary static IP for direct USB RNDIS (Linux side).
pub const USB_IP_PRIMARY: &str = "10.0.0.2";
/// Primary CIDR for the direct RNDIS subnet.
pub const USB_CIDR_PRIMARY: &str = "10.0.0.2/24";
/// Secondary static IP for Windows ICS subnet.
pub const USB_IP_ICS: &str = "192.168.137.2";
/// Secondary CIDR for the ICS subnet.
pub const USB_CIDR_ICS: &str = "192.168.137.2/24";
/// Default gateway via the RNDIS host.
pub const USB_GATEWAY: &str = "10.0.0.1";
/// DNS server.
pub const DNS_SERVER: &str = "8.8.8.8";
/// Ping target for internet connectivity check.
pub const PING_TARGET: &str = "8.8.8.8";
/// DNS resolution test hostname.
pub const DNS_TEST_HOST: &str = "google.com";
/// ICS subnet prefix (Windows Internet Connection Sharing).
pub const ICS_SUBNET_PREFIX: &str = "192.168.137.";

// ---------------------------------------------------------------------------
// USB0 interface state
// ---------------------------------------------------------------------------

/// Whether the usb0 interface exists and its link state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Usb0State {
    /// Interface does not exist (no USB gadget / not connected).
    Absent,
    /// Interface exists but link is DOWN.
    Down,
    /// Interface exists and link is UP (RNDIS connected).
    Up,
}

/// Internet connectivity status.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InternetStatus {
    /// Not checked yet.
    Unknown,
    /// Ping succeeds, internet reachable.
    Online,
    /// Ping fails, no internet.
    Offline,
}

/// Format USB IP for e-ink display. Always shown.
pub fn format_usb_ip(ip: Option<&str>) -> String {
    if let Some(ip) = ip {
        format!("USB:{ip} :8080")
    } else {
        "USB:--".to_string()
    }
}

/// Format BT IP for e-ink display. Empty when not connected.
pub fn format_bt_ip(ip: Option<&str>) -> String {
    if let Some(ip) = ip {
        format!("BT:{ip}")
    } else {
        String::new()
    }
}

// ---------------------------------------------------------------------------
// Pure functions: command builders and parsers (testable everywhere)
// ---------------------------------------------------------------------------

/// Build `ip addr show usb0` args.
pub fn build_ip_addr_show_args() -> Vec<String> {
    vec!["-4".into(), "addr".into(), "show".into(), "usb0".into()]
}

/// Build `ip addr add <cidr> dev usb0` args.
pub fn build_ip_add_args(cidr: &str) -> Vec<String> {
    vec![
        "addr".into(),
        "add".into(),
        cidr.into(),
        "dev".into(),
        "usb0".into(),
    ]
}

/// Build `ip link set usb0 up` args.
pub fn build_link_up_args() -> Vec<String> {
    vec!["link".into(), "set".into(), "usb0".into(), "up".into()]
}

/// Build `ip route add default via <gw> dev usb0` args.
pub fn build_default_route_args(gateway: &str) -> Vec<String> {
    vec![
        "route".into(),
        "add".into(),
        "default".into(),
        "via".into(),
        gateway.into(),
        "dev".into(),
        "usb0".into(),
    ]
}

/// Build `ip route replace default via <gw> dev usb0` args.
pub fn build_default_route_replace_args(gateway: &str) -> Vec<String> {
    vec![
        "route".into(),
        "replace".into(),
        "default".into(),
        "via".into(),
        gateway.into(),
        "dev".into(),
        "usb0".into(),
    ]
}

/// Build ping command args: `ping -c 1 -W <timeout_secs> <target>`.
pub fn build_ping_args(target: &str, timeout_secs: u32) -> Vec<String> {
    vec![
        "-c".into(),
        "1".into(),
        "-W".into(),
        timeout_secs.to_string(),
        target.into(),
    ]
}

/// Build DNS resolution test args: `getent hosts <hostname>`.
pub fn build_dns_test_args(hostname: &str) -> Vec<String> {
    vec!["hosts".into(), hostname.into()]
}

/// Build the resolv.conf content with a nameserver entry.
pub fn build_resolv_conf(dns: &str) -> String {
    format!("# Generated by oxigotchi\nnameserver {dns}\n")
}

/// Parse all IPv4 addresses from `ip -4 addr show usb0` output.
///
/// Returns a list of bare IPs (no CIDR suffix).
pub fn parse_ips_from_output(output: &str) -> Vec<String> {
    let mut ips = Vec::new();
    for line in output.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("inet ") {
            if let Some(addr_cidr) = rest.split_whitespace().next() {
                if let Some(addr) = addr_cidr.split('/').next() {
                    ips.push(addr.to_string());
                }
            }
        }
    }
    ips
}

/// Check if a list of IPs contains a specific address.
pub fn has_ip(ips: &[String], target: &str) -> bool {
    ips.iter().any(|ip| ip == target)
}

/// Detect if ICS changed our IP (we got a 192.168.137.x address from DHCP
/// instead of our static config).
pub fn detect_ics_dhcp(ips: &[String]) -> bool {
    ips.iter()
        .any(|ip| ip.starts_with(ICS_SUBNET_PREFIX) && ip != USB_IP_ICS)
}

/// Parse usb0 link operstate from sysfs content.
///
/// The file contains one of: "up", "down", "unknown", etc.
pub fn parse_operstate(content: &str) -> Usb0State {
    match content.trim() {
        "up" => Usb0State::Up,
        _ => Usb0State::Down,
    }
}

/// Determine which IPs are missing from the current configuration.
///
/// Returns `(need_primary, need_ics)`.
pub fn missing_ips(current_ips: &[String]) -> (bool, bool) {
    let need_primary = !has_ip(current_ips, USB_IP_PRIMARY);
    let need_ics = !has_ip(current_ips, USB_IP_ICS);
    (need_primary, need_ics)
}

// ---------------------------------------------------------------------------
// System command execution (unix-only)
// ---------------------------------------------------------------------------

/// Run `ip` with the given arguments. Returns Ok(stdout) or Err(stderr).
#[cfg(unix)]
fn run_ip(args: &[String]) -> Result<String, String> {
    let output = std::process::Command::new("ip")
        .args(args)
        .output()
        .map_err(|e| format!("failed to run ip: {e}"))?;
    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).to_string())
    }
}

/// Run `ping` with the given arguments. Returns true if exit code 0.
#[cfg(unix)]
fn run_ping(args: &[String]) -> bool {
    std::process::Command::new("ping")
        .args(args)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Run `getent` with the given arguments. Returns true if exit code 0.
#[cfg(unix)]
fn run_getent(args: &[String]) -> bool {
    std::process::Command::new("getent")
        .args(args)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Check if usb0 interface exists (unix-only).
#[cfg(unix)]
fn usb0_exists() -> bool {
    std::path::Path::new(USB0_SYSFS_PATH).exists()
}

/// Stub: usb0 never exists on non-unix.
#[cfg(not(unix))]
fn usb0_exists() -> bool {
    false
}

/// Read usb0 operstate from sysfs (unix-only).
#[cfg(unix)]
fn read_operstate() -> Usb0State {
    match std::fs::read_to_string(USB0_OPERSTATE_PATH) {
        Ok(content) => parse_operstate(&content),
        Err(_) => Usb0State::Absent,
    }
}

/// Stub: always Absent on non-unix.
#[cfg(not(unix))]
fn read_operstate() -> Usb0State {
    Usb0State::Absent
}

/// Write DNS config to /etc/resolv.conf (unix-only).
#[cfg(unix)]
fn write_resolv_conf(dns: &str) -> Result<(), String> {
    let content = build_resolv_conf(dns);
    std::fs::write("/etc/resolv.conf", content)
        .map_err(|e| format!("failed to write /etc/resolv.conf: {e}"))
}

// ---------------------------------------------------------------------------
// NetworkManager — the main state machine
// ---------------------------------------------------------------------------

/// USB RNDIS network manager.
pub struct NetworkManager {
    /// Current usb0 interface state.
    pub usb0_state: Usb0State,
    /// Known IP addresses on usb0.
    pub usb0_ips: Vec<String>,
    /// Internet connectivity status.
    pub internet: InternetStatus,
    /// Last time we successfully applied IPs.
    pub last_ip_apply: Option<Instant>,
    /// Last time we checked internet connectivity.
    pub last_inet_check: Option<Instant>,
    /// Number of consecutive health check failures.
    pub consecutive_failures: u32,
    /// Log of connectivity state changes.
    pub last_state_change: Option<Instant>,
}

impl NetworkManager {
    /// Create a new network manager.
    pub fn new() -> Self {
        Self {
            usb0_state: Usb0State::Absent,
            usb0_ips: Vec::new(),
            internet: InternetStatus::Unknown,
            last_ip_apply: None,
            last_inet_check: None,
            consecutive_failures: 0,
            last_state_change: None,
        }
    }

    /// Probe usb0 interface state and update internal state.
    pub fn probe(&mut self) -> Usb0State {
        if !usb0_exists() {
            if self.usb0_state != Usb0State::Absent {
                info!("usb0 disappeared");
                self.on_state_change();
            }
            self.usb0_state = Usb0State::Absent;
            self.usb0_ips.clear();
            self.internet = InternetStatus::Offline;
            return self.usb0_state;
        }

        let new_state = read_operstate();
        if new_state != self.usb0_state {
            info!("usb0 state: {:?} -> {:?}", self.usb0_state, new_state);
            self.on_state_change();
        }
        self.usb0_state = new_state;

        // Refresh IPs
        self.refresh_ips();

        self.usb0_state
    }

    /// Refresh the known IP addresses on usb0.
    pub fn refresh_ips(&mut self) {
        #[cfg(unix)]
        {
            let args = build_ip_addr_show_args();
            if let Ok(output) = run_ip(&args) {
                self.usb0_ips = parse_ips_from_output(&output);
            }
        }
    }

    /// Apply the static dual-IP configuration on usb0.
    ///
    /// Sets 10.0.0.2/24 and 192.168.137.2/24 if missing.
    /// Also brings the link up and sets default gateway + DNS.
    pub fn apply_ip_config(&mut self) -> Result<(), String> {
        if self.usb0_state == Usb0State::Absent {
            return Err("usb0 interface does not exist".into());
        }

        // Bring link up first
        #[cfg(unix)]
        {
            let args = build_link_up_args();
            let _ = run_ip(&args);
        }

        let (need_primary, need_ics) = missing_ips(&self.usb0_ips);

        if need_primary {
            info!("adding primary IP {USB_CIDR_PRIMARY} to usb0");
            #[cfg(unix)]
            {
                let args = build_ip_add_args(USB_CIDR_PRIMARY);
                if let Err(e) = run_ip(&args) {
                    warn!("ip addr add {USB_CIDR_PRIMARY}: {e}");
                }
            }
        }

        if need_ics {
            info!("adding ICS IP {USB_CIDR_ICS} to usb0");
            #[cfg(unix)]
            {
                let args = build_ip_add_args(USB_CIDR_ICS);
                if let Err(e) = run_ip(&args) {
                    warn!("ip addr add {USB_CIDR_ICS}: {e}");
                }
            }
        }

        // Set default gateway
        #[cfg(unix)]
        {
            let args = build_default_route_replace_args(USB_GATEWAY);
            if let Err(e) = run_ip(&args) {
                warn!("ip route replace default: {e}");
            }
        }

        // Set DNS
        #[cfg(unix)]
        {
            if let Err(e) = write_resolv_conf(DNS_SERVER) {
                warn!("write resolv.conf: {e}");
            }
        }

        self.last_ip_apply = Some(Instant::now());

        // Refresh IPs after applying
        self.refresh_ips();

        if need_primary || need_ics {
            info!(
                "IP config applied: needed_primary={need_primary}, needed_ics={need_ics}"
            );
        }

        Ok(())
    }

    /// Check internet connectivity via ping + DNS.
    ///
    /// Returns the new status.
    pub fn check_internet(&mut self) -> InternetStatus {
        // Ping regardless of usb0 state — internet may come via bnep0 (BT tether)
        let ping_ok;
        #[cfg(unix)]
        {
            let args = build_ping_args(PING_TARGET, 3);
            ping_ok = run_ping(&args);
        }
        #[cfg(not(unix))]
        {
            ping_ok = false;
        }

        let old = self.internet;
        self.internet = if ping_ok {
            InternetStatus::Online
        } else {
            InternetStatus::Offline
        };

        if self.internet != old {
            info!("internet: {:?} -> {:?}", old, self.internet);
            self.on_state_change();
        }

        self.last_inet_check = Some(Instant::now());
        self.internet
    }

    /// Run DNS resolution test. Returns true if DNS works.
    pub fn check_dns(&self) -> bool {
        #[cfg(unix)]
        {
            let args = build_dns_test_args(DNS_TEST_HOST);
            return run_getent(&args);
        }
        #[cfg(not(unix))]
        {
            false
        }
    }

    /// Detect if ICS reassigned our IP via DHCP.
    pub fn detect_ics_change(&self) -> bool {
        detect_ics_dhcp(&self.usb0_ips)
    }

    /// Periodic health check: re-apply IPs if they disappeared.
    ///
    /// Call this once per epoch.
    pub fn health_check(&mut self) {
        let prev_state = self.usb0_state;
        self.probe();

        if self.usb0_state == Usb0State::Absent {
            self.consecutive_failures = 0;
            return;
        }

        let (need_primary, need_ics) = missing_ips(&self.usb0_ips);
        if need_primary || need_ics {
            warn!(
                "usb0 IPs missing (primary={}, ics={}), re-applying",
                need_primary, need_ics
            );
            let _ = self.apply_ip_config();
            self.consecutive_failures += 1;
        } else {
            self.consecutive_failures = 0;
        }

        // Log if interface came back
        if prev_state == Usb0State::Absent && self.usb0_state != Usb0State::Absent {
            info!("usb0 appeared, applying IP config");
            let _ = self.apply_ip_config();
        }
    }

    /// Get USB IP display string.
    pub fn usb_ip_str(&self) -> String {
        let usb_ip = self.usb0_ips.first().map(|s| s.as_str());
        format_usb_ip(usb_ip)
    }

    /// Record a state change timestamp.
    fn on_state_change(&mut self) {
        self.last_state_change = Some(Instant::now());
    }

    /// Short status string for logging/display.
    pub fn status_str(&self) -> &'static str {
        match (self.usb0_state, self.internet) {
            (Usb0State::Absent, _) => "USB --",
            (Usb0State::Down, _) => "USB DN",
            (Usb0State::Up, InternetStatus::Online) => "USB OK",
            (Usb0State::Up, InternetStatus::Offline) => "USB NI",
            (Usb0State::Up, InternetStatus::Unknown) => "USB UP",
        }
    }
}

impl Default for NetworkManager {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ===== New independent IP formatter tests =====

    #[test]
    fn test_format_usb_ip_with_ip() {
        assert_eq!(format_usb_ip(Some("10.0.0.2")), "USB:10.0.0.2 :8080");
    }

    #[test]
    fn test_format_usb_ip_no_ip() {
        assert_eq!(format_usb_ip(None), "USB:--");
    }

    #[test]
    fn test_format_bt_ip_with_ip() {
        assert_eq!(format_bt_ip(Some("192.168.44.128")), "BT:192.168.44.128");
    }

    #[test]
    fn test_format_bt_ip_no_ip() {
        assert_eq!(format_bt_ip(None), "");
    }

    // ===== IP parsing tests =====

    #[test]
    fn test_parse_ips_typical_usb0_output() {
        let output = r#"3: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500
    inet 10.0.0.2/24 brd 10.0.0.255 scope global usb0
       valid_lft forever preferred_lft forever
    inet 192.168.137.2/24 brd 192.168.137.255 scope global secondary usb0
       valid_lft forever preferred_lft forever"#;
        let ips = parse_ips_from_output(output);
        assert_eq!(ips, vec!["10.0.0.2", "192.168.137.2"]);
    }

    #[test]
    fn test_parse_ips_single_ip() {
        let output = "    inet 10.0.0.2/24 brd 10.0.0.255 scope global usb0\n";
        let ips = parse_ips_from_output(output);
        assert_eq!(ips, vec!["10.0.0.2"]);
    }

    #[test]
    fn test_parse_ips_no_inet_line() {
        let output = "3: usb0: <BROADCAST,MULTICAST> mtu 1500\n    link/ether ...\n";
        let ips = parse_ips_from_output(output);
        assert!(ips.is_empty());
    }

    #[test]
    fn test_parse_ips_empty_output() {
        let ips = parse_ips_from_output("");
        assert!(ips.is_empty());
    }

    #[test]
    fn test_parse_ips_ics_dhcp_address() {
        let output = "    inet 192.168.137.50/24 brd 192.168.137.255 scope global usb0\n";
        let ips = parse_ips_from_output(output);
        assert_eq!(ips, vec!["192.168.137.50"]);
    }

    // ===== has_ip tests =====

    #[test]
    fn test_has_ip_present() {
        let ips = vec!["10.0.0.2".to_string(), "192.168.137.2".to_string()];
        assert!(has_ip(&ips, "10.0.0.2"));
        assert!(has_ip(&ips, "192.168.137.2"));
    }

    #[test]
    fn test_has_ip_absent() {
        let ips = vec!["10.0.0.2".to_string()];
        assert!(!has_ip(&ips, "192.168.137.2"));
    }

    #[test]
    fn test_has_ip_empty() {
        let ips: Vec<String> = vec![];
        assert!(!has_ip(&ips, "10.0.0.2"));
    }

    // ===== missing_ips tests =====

    #[test]
    fn test_missing_ips_both_missing() {
        let ips: Vec<String> = vec![];
        let (p, i) = missing_ips(&ips);
        assert!(p);
        assert!(i);
    }

    #[test]
    fn test_missing_ips_primary_present() {
        let ips = vec!["10.0.0.2".to_string()];
        let (p, i) = missing_ips(&ips);
        assert!(!p);
        assert!(i);
    }

    #[test]
    fn test_missing_ips_both_present() {
        let ips = vec!["10.0.0.2".to_string(), "192.168.137.2".to_string()];
        let (p, i) = missing_ips(&ips);
        assert!(!p);
        assert!(!i);
    }

    #[test]
    fn test_missing_ips_ics_only() {
        let ips = vec!["192.168.137.2".to_string()];
        let (p, i) = missing_ips(&ips);
        assert!(p);
        assert!(!i);
    }

    // ===== ICS detection tests =====

    #[test]
    fn test_detect_ics_dhcp_no_ics() {
        let ips = vec!["10.0.0.2".to_string()];
        assert!(!detect_ics_dhcp(&ips));
    }

    #[test]
    fn test_detect_ics_dhcp_static_ics() {
        let ips = vec!["10.0.0.2".to_string(), "192.168.137.2".to_string()];
        assert!(!detect_ics_dhcp(&ips)); // .2 is our static, not DHCP
    }

    #[test]
    fn test_detect_ics_dhcp_foreign_ics() {
        let ips = vec!["192.168.137.50".to_string()];
        assert!(detect_ics_dhcp(&ips)); // .50 is DHCP-assigned, not our .2
    }

    #[test]
    fn test_detect_ics_dhcp_empty() {
        let ips: Vec<String> = vec![];
        assert!(!detect_ics_dhcp(&ips));
    }

    // ===== operstate parsing tests =====

    #[test]
    fn test_parse_operstate_up() {
        assert_eq!(parse_operstate("up\n"), Usb0State::Up);
    }

    #[test]
    fn test_parse_operstate_down() {
        assert_eq!(parse_operstate("down\n"), Usb0State::Down);
    }

    #[test]
    fn test_parse_operstate_unknown() {
        assert_eq!(parse_operstate("unknown\n"), Usb0State::Down);
    }

    #[test]
    fn test_parse_operstate_empty() {
        assert_eq!(parse_operstate(""), Usb0State::Down);
    }

    // ===== Command builder tests =====

    #[test]
    fn test_build_ip_addr_show_args() {
        let args = build_ip_addr_show_args();
        assert_eq!(args, vec!["-4", "addr", "show", "usb0"]);
    }

    #[test]
    fn test_build_ip_add_args_primary() {
        let args = build_ip_add_args("10.0.0.2/24");
        assert_eq!(args, vec!["addr", "add", "10.0.0.2/24", "dev", "usb0"]);
    }

    #[test]
    fn test_build_ip_add_args_ics() {
        let args = build_ip_add_args("192.168.137.2/24");
        assert_eq!(args, vec!["addr", "add", "192.168.137.2/24", "dev", "usb0"]);
    }

    #[test]
    fn test_build_link_up_args() {
        let args = build_link_up_args();
        assert_eq!(args, vec!["link", "set", "usb0", "up"]);
    }

    #[test]
    fn test_build_default_route_args() {
        let args = build_default_route_args("10.0.0.1");
        assert_eq!(
            args,
            vec!["route", "add", "default", "via", "10.0.0.1", "dev", "usb0"]
        );
    }

    #[test]
    fn test_build_default_route_replace_args() {
        let args = build_default_route_replace_args("10.0.0.1");
        assert_eq!(
            args,
            vec![
                "route", "replace", "default", "via", "10.0.0.1", "dev", "usb0"
            ]
        );
    }

    #[test]
    fn test_build_ping_args() {
        let args = build_ping_args("8.8.8.8", 3);
        assert_eq!(args, vec!["-c", "1", "-W", "3", "8.8.8.8"]);
    }

    #[test]
    fn test_build_ping_args_custom_timeout() {
        let args = build_ping_args("1.1.1.1", 5);
        assert_eq!(args, vec!["-c", "1", "-W", "5", "1.1.1.1"]);
    }

    #[test]
    fn test_build_dns_test_args() {
        let args = build_dns_test_args("google.com");
        assert_eq!(args, vec!["hosts", "google.com"]);
    }

    #[test]
    fn test_build_resolv_conf() {
        let content = build_resolv_conf("8.8.8.8");
        assert_eq!(content, "# Generated by oxigotchi\nnameserver 8.8.8.8\n");
    }

    #[test]
    fn test_build_resolv_conf_custom_dns() {
        let content = build_resolv_conf("1.1.1.1");
        assert!(content.contains("nameserver 1.1.1.1"));
    }

    // ===== Interface existence check =====

    #[test]
    fn test_usb0_exists_non_unix() {
        // On non-unix (test host), usb0 never exists
        assert!(!usb0_exists());
    }

    // ===== NetworkManager state machine tests =====

    #[test]
    fn test_network_manager_default() {
        let nm = NetworkManager::new();
        assert_eq!(nm.usb0_state, Usb0State::Absent);
        assert!(nm.usb0_ips.is_empty());
        assert_eq!(nm.internet, InternetStatus::Unknown);
        assert_eq!(nm.consecutive_failures, 0);
    }

    #[test]
    fn test_network_manager_probe_no_usb0() {
        let mut nm = NetworkManager::new();
        let state = nm.probe();
        assert_eq!(state, Usb0State::Absent);
        assert!(nm.usb0_ips.is_empty());
    }

    #[test]
    fn test_network_manager_apply_config_absent() {
        let mut nm = NetworkManager::new();
        let result = nm.apply_ip_config();
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("does not exist"));
    }

    #[test]
    fn test_network_manager_apply_config_down() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Down;
        // On non-unix this won't actually run ip commands, but shouldn't panic
        let result = nm.apply_ip_config();
        assert!(result.is_ok());
        assert!(nm.last_ip_apply.is_some());
    }

    #[test]
    fn test_network_manager_apply_config_up() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Up;
        let result = nm.apply_ip_config();
        assert!(result.is_ok());
    }

    #[test]
    fn test_network_manager_check_internet_absent() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Absent;
        let status = nm.check_internet();
        // On Pi, usb0 absent means no route to 8.8.8.8 -> Offline.
        // On WSL/desktop Linux, ping may succeed via eth0/wlan0 -> Online.
        // Both are valid — check_internet pings regardless of usb0 state.
        assert!(
            status == InternetStatus::Offline || status == InternetStatus::Online,
            "expected Offline or Online, got {:?}",
            status
        );
    }

    #[test]
    fn test_network_manager_check_internet_records_time() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Up;
        nm.check_internet();
        assert!(nm.last_inet_check.is_some());
    }

    #[test]
    fn test_network_manager_health_check_absent() {
        let mut nm = NetworkManager::new();
        nm.health_check();
        assert_eq!(nm.usb0_state, Usb0State::Absent);
        assert_eq!(nm.consecutive_failures, 0);
    }

    #[test]
    fn test_network_manager_health_check_with_ips_present() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Up;
        nm.usb0_ips = vec!["10.0.0.2".to_string(), "192.168.137.2".to_string()];
        // On non-unix probe() will set state to Absent, so test the
        // missing_ips logic directly
        let (p, i) = missing_ips(&nm.usb0_ips);
        assert!(!p);
        assert!(!i);
    }

    #[test]
    fn test_network_manager_health_check_missing_ics() {
        let mut nm = NetworkManager::new();
        nm.usb0_ips = vec!["10.0.0.2".to_string()];
        let (p, i) = missing_ips(&nm.usb0_ips);
        assert!(!p);
        assert!(i); // ICS missing, would trigger re-apply
    }

    #[test]
    fn test_network_manager_detect_ics_change() {
        let mut nm = NetworkManager::new();
        nm.usb0_ips = vec!["192.168.137.50".to_string()];
        assert!(nm.detect_ics_change());

        nm.usb0_ips = vec!["10.0.0.2".to_string(), "192.168.137.2".to_string()];
        assert!(!nm.detect_ics_change());
    }

    #[test]
    fn test_network_manager_status_str_absent() {
        let nm = NetworkManager::new();
        assert_eq!(nm.status_str(), "USB --");
    }

    #[test]
    fn test_network_manager_status_str_down() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Down;
        assert_eq!(nm.status_str(), "USB DN");
    }

    #[test]
    fn test_network_manager_status_str_up_online() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Up;
        nm.internet = InternetStatus::Online;
        assert_eq!(nm.status_str(), "USB OK");
    }

    #[test]
    fn test_network_manager_status_str_up_offline() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Up;
        nm.internet = InternetStatus::Offline;
        assert_eq!(nm.status_str(), "USB NI");
    }

    #[test]
    fn test_network_manager_status_str_up_unknown() {
        let mut nm = NetworkManager::new();
        nm.usb0_state = Usb0State::Up;
        nm.internet = InternetStatus::Unknown;
        assert_eq!(nm.status_str(), "USB UP");
    }

    // ===== Constants tests =====

    #[test]
    fn test_constants() {
        assert_eq!(USB0_SYSFS_PATH, "/sys/class/net/usb0");
        assert_eq!(USB_IP_PRIMARY, "10.0.0.2");
        assert_eq!(USB_IP_ICS, "192.168.137.2");
        assert_eq!(USB_GATEWAY, "10.0.0.1");
        assert_eq!(DNS_SERVER, "8.8.8.8");
        assert_eq!(ICS_SUBNET_PREFIX, "192.168.137.");
    }

    // ===== Dual-IP configuration command sequence test =====

    #[test]
    fn test_dual_ip_command_sequence() {
        // Verify the full sequence of commands that would be issued
        // to configure usb0 from scratch
        let link_up = build_link_up_args();
        assert_eq!(link_up, vec!["link", "set", "usb0", "up"]);

        let add_primary = build_ip_add_args(USB_CIDR_PRIMARY);
        assert_eq!(
            add_primary,
            vec!["addr", "add", "10.0.0.2/24", "dev", "usb0"]
        );

        let add_ics = build_ip_add_args(USB_CIDR_ICS);
        assert_eq!(
            add_ics,
            vec!["addr", "add", "192.168.137.2/24", "dev", "usb0"]
        );

        let route = build_default_route_replace_args(USB_GATEWAY);
        assert_eq!(
            route,
            vec![
                "route", "replace", "default", "via", "10.0.0.1", "dev", "usb0"
            ]
        );

        let resolv = build_resolv_conf(DNS_SERVER);
        assert!(resolv.contains("nameserver 8.8.8.8"));
    }

    // ===== Internet check result handling =====

    #[test]
    fn test_internet_transitions() {
        let mut nm = NetworkManager::new();
        assert_eq!(nm.internet, InternetStatus::Unknown);

        // Ping 8.8.8.8: fails on Windows (no ping), fails on Pi without
        // internet, but may succeed on WSL/desktop Linux with internet.
        nm.usb0_state = Usb0State::Up;
        nm.check_internet();
        assert!(
            nm.internet == InternetStatus::Offline || nm.internet == InternetStatus::Online,
            "expected Offline or Online after check, got {:?}",
            nm.internet
        );

        // Simulate coming back online manually
        nm.internet = InternetStatus::Online;
        assert_eq!(nm.status_str(), "USB OK");
    }

    // ===== Default trait test =====

    #[test]
    fn test_default_trait() {
        let nm = NetworkManager::default();
        assert_eq!(nm.usb0_state, Usb0State::Absent);
    }
}
